name: Alpha Pipeline
on:
  push:
    branches:
      - 'alpha*'
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test solution
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.build-and-test-action
        with:
          nuget-username: automation
          src-dir: ./src/code
          build-environment: dev
          coverage-threshold: 90
          repo-organisation: architected
