name: Alpha Pipeline
on:
  push:
    branches:
      - 'alpha*'
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test solution
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - uses: ./.build-and-test-action
        with:
          nuget-username: automation
          src-dir: ./src/code
          build-environment: dev
          coverage-threshold: 90
          repo-organisation: architected
          team-pat: ${{ secrets.TEAM_PAT}}
