name: Alpha Pipeline
on:
  push:
    branches:
      - 'alpha*'
env:
  NUGET_USERNAME: automation
  SRC_DIR: ./src/code
  BUILD_ENVIRONMENT: dev
  COVERAGE_THRESHOLD: 90
  REPO_ORGANISATION: architected
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test solution
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - uses: ./build-and-test-action
        with:
          nuget-username: ${{ env.NUGET_USERNAME }}
          src-dir: ${{ env.SRC_DIR }}
          build-environment: ${{ env.BUILD_ENVIRONMENT }}
          coverage-threshold: ${{ env.COVERAGE_THRESHOLD }}
          repo-organisation: ${{ env.REPO_ORGANISATION }}
